### ISSUE TITLE
There is no Way to build the base-ros

### ISSUE THREAD

**Issue by mauringo** [boschrexroth/ctrlx-automation-sdk-ros2#3]
Hello,

There is no way to build the app base-ros out of the box. The documentation is missing/the snapcraft is missing some part. 
It is working on your machine because probably  you have already  installed Humble and then building with --destructive-mode you have already the repos set. 
https://docs.ros.org/en/humble/Installation/Ubuntu-Install-Debians.html

Please fix the snapcraft.yaml: a possible way is the following: https://github.com/facontidavide/PlotJuggler/blob/main/snap/snapcraft.yaml

Installing ROS on the building machine e.g. follwing: https://docs.ros.org/en/humble/Installation/Ubuntu-Install-Debians.html and installing  ros-humble-desktop solves the issue. 

Mauro

**Comment by rureverek** [comment]
Hi, if your issue is: "field source required in parts.ros-base configuration" try the version 6.x of snapcraft.

**Comment by mauringo** [comment]
@rureverek nope. the problem is that i had no ros2 humble  installed in the building machine :)
